[project]
name = "deep_peak_sieve"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "audian",
    "audioio",
    "ipython>=9.0.2",
]

[tool.uv.sources]
audioio = { git = "https://github.com/bendalab/audioio" }
audian = { git = "https://github.com/bendalab/audian" }

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]

[project.scripts]
collect_peaks = "deep_peak_sieve.collection.collect_peaks:app"
sample_peaks = "deep_peak_sieve.sampling.sample_peaks:app"
label_peaks = "deep_peak_sieve.labeling.label_peaks:app"
explore = "deep_peak_sieve.exploration:app"
