[project]
name = "pulses"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audian",
    "audioio",
    "ipython>=9.0.2",
    "thunderfish",
    "thunderlab",
]

[tool.uv.sources]
audioio = { git = "https://github.com/bendalab/audioio" }
thunderlab = { git = "https://github.com/bendalab/thunderlab" }
thunderfish = { git = "https://github.com/bendalab/thunderfish" }
audian = { git = "https://github.com/bendalab/audian" }

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
